name: BuildAndTest

on: [ push ]

jobs:
  build:
    name: BuildAndTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.5.x', '1.13.x' ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build .
      - run: go test .