name: glog

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        go: [ '1.5.x', '1.13.x' ]
    name: BuildAndTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
      - uses: actions/checkout@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go build .
      - run: go test .

  codecov:
    strategy:
      matrix:
        go: [ '1.13.x' ]
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
      - uses: actions/checkout@v2
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true